// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWON0-RJs5_-DxsAyXxPlaY-wpdVSHAtE',
    appId: '1:97472343187:web:fafe8c8bd15aaa09033166',
    messagingSenderId: '97472343187',
    projectId: 'aas-mobileapp',
    authDomain: 'aas-mobileapp.firebaseapp.com',
    storageBucket: 'aas-mobileapp.firebasestorage.app',
    measurementId: 'G-XS2GS4QKQ8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWDYNsrTwX6DKYnsj8Ld35tIDg5I1AejY',
    appId: '1:97472343187:ios:78a9b6dbe83eb1c5033166',
    messagingSenderId: '97472343187',
    projectId: 'aas-mobileapp',
    storageBucket: 'aas-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.thesisProjectApp2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWON0-RJs5_-DxsAyXxPlaY-wpdVSHAtE',
    appId: '1:97472343187:web:9851b13e66e84d98033166',
    messagingSenderId: '97472343187',
    projectId: 'aas-mobileapp',
    authDomain: 'aas-mobileapp.firebaseapp.com',
    storageBucket: 'aas-mobileapp.firebasestorage.app',
    measurementId: 'G-2K07NNYPEY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDYNsrTwX6DKYnsj8Ld35tIDg5I1AejY',
    appId: '1:97472343187:ios:78a9b6dbe83eb1c5033166',
    messagingSenderId: '97472343187',
    projectId: 'aas-mobileapp',
    storageBucket: 'aas-mobileapp.firebasestorage.app',
    iosBundleId: 'com.example.thesisProjectApp2025',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJyleAf9KRJNxfwwXCdNnHA35GBhgMP-o',
    appId: '1:97472343187:android:5ab9ea391bc259e4033166',
    messagingSenderId: '97472343187',
    projectId: 'aas-mobileapp',
    storageBucket: 'aas-mobileapp.firebasestorage.app',
  );

}